### ISSUE TITLE
Error message - unknown account specifier 

### ISSUE THREAD

**Issue by phaymond** [wealdtech/ethdo#100]
I'm trying to run the following command on Ethdo: 

**./ethdo account derive --mnemonic="your 12 or 24 word mnemonic here" --path="m/12381/3600/0/0"**

When I put in my seed phrase, it keeps giving me this error message: 

**"Error: failed to process: failed to derive account: unknown account specifier"** with the first word of my seed phrase. 

What's odd is that the command works when using a newer seed phrase, as it produces a public key. Is the issue my seed phrase when I created it the first time with Staked.us or is this an ethdo error? 

I checked my seed on another ethereum program and it worked, so I'm not sure why I'm getting this.

**Comment by mcdee** [comment]
What version of ethdo are you using?  Support for 12-word phrases was added in 1.31.0.  Also, are you putting quotes around your mnemonic as per the command?

This appears to be okay with a local test:

```
ethdo version
1.31.0
ethdo account derive --mnemonic="abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" --path=m/12381/3600/0/0
Public key: 0x8ebe599559cbf3abbc6a72b25d8bc13fd9b5075283fcd9ec47b2a0bf6c5148a2e9e615b181e5b2c03abe63818ef70c61
```

**Comment by phaymond** [comment]
I'm using the latest version 1.31. Yes I put quotes around the mnemonic. 

Is it possible the program I used to generate the seed didn't create it correctly? 

What does the error message from Ethdo mean?

**Comment by mcdee** [comment]
The message means that ethdo only saw the first word of the mnemonic, and is trying to use that as a general account specifier (e.g. an account name or validator index) rather than a full mnemonic.  Can you try running the commands in my prior message and supplying the output?

The mnemonic is likely fine, it seems to be an issue with the input.

**Comment by phaymond** [comment]
Thank you for clarifying. I ran your commands and it worked exactly the same for me. 

Now I ran the same command again with my seed & it says: 

>  ./eth: No such file or directory

That doesn't sound good...

**Comment by mcdee** [comment]
`eth` is not the command, it is `ethdo`.  You should take the command that worked and swap out the mnemonic, making no other changes.

**Comment by phaymond** [comment]
I did it again and got this error message: 

`Error: failed to process: failed to derive account: mnemonic is invalid`

Then I ran your command and mine again. Somehow the second time it generated the public key correctly. I'm not sure why but thank you so much for your help.
