### ISSUE TITLE
Deposit data file is not valid for launchpad (distributed wallet)

### ISSUE THREAD

**Issue by vuonghoainam** [wealdtech/ethdo#102]
Hi, I'm trying to setup a system with 2 vouch & 5 dirk (threshold 3, participants 5)
I'm using ethdo version 1.31.0 (in [docker image 1.30.0](https://hub.docker.com/r/wealdtech/ethdo/tags)) to run the command.

My current problem now is that after create wallet (distributed type), create account and able to sign, the JSON output file from my `ethdo validator depositdata` is not valid for both goerli and mainnet launchpad.

Command to create deposit data:
```
ethdo validator depositdata   --depositvalue 32Ether   --remote=dirk1:13141   --server-ca-cert /config/certs/dirk_authority.crt   --client-cert /config/certs/vouch1.crt   --client-key /config/certs/vouch1.key   --validatoraccount DistributedWallet/val-1   --launchpad   --forkversion ${FORK_VERSION}   --withdrawaladdress ${WITHDRAWAL_ADDRESS} > /config/depositdata/deposit-val-1.json

jq -n '[inputs|add]' config/depositdata/deposit-val-1.json > config/depositdata/deposits.json
```

- Mainet - `FORK_VERSION=0x00000000`
```
ethdo deposit verify --data=/config/depositdata/deposit-val-1.json 

Withdrawal public key or address not supplied; withdrawal credentials NOT checked
Amount verified
Validator public key not suppled; NOT checked
Deposit data root verified
Fork version verified
Error attempting to verify deposit "": failed to generate deposit message root: DepositMessage.WithdrawalCredentials (bytes array does not have the correct length): expected 32 and 0 found
```
- Goerli - `FORK_VERSION=0x00001020`
```
ethdo deposit verify --data=/config/depositdata/deposit-val-1.json 
Withdrawal public key or address not supplied; withdrawal credentials NOT checked
Amount verified
Validator public key not suppled; NOT checked
Deposit data root verified
Fork version incorrect
Deposit failed verification
```
When I try to compare the `deposit_data.json` file with the one I successfully generated/ deposited, the notable differences are:
- Key `eth2_network_name` has to be `network_name`
- Value  `prater` has to be `goerli`
- `deposit_cli_version` value: The successfully deposit one is `2.5.0`, but the failed ones above is `1.1.0`

Can you share with me how to get a valid deposit_data file for both goerli and mainnet?

Thanks

**Comment by mcdee** [comment]
The command is attempting to recreate your deposit message but failing to do so because you haven't provided the withdrawal address to the verification command.  You can fix this by adding `--withdrawaladdress=0x...` to the `deposit verify` command.

Separately, I will update the code so that it provides a suitable message rather than erroring in this situation.
