### ISSUE TITLE
Offline preparation no longer works

### ISSUE THREAD

**Issue by jagmot** [wealdtech/ethdo#103]
ethdo validator credentials set --prepare-offline
Connections to remote beacon nodes should be secure.  This warning can be silenced with --allow-insecure-connections
Error: failed to process: failed to connect to beacon node: failed to confirm node connection: failed to fetch genesis: failed to obtain genesis

ethdo validator exit --prepare-offline
Error: failed to process: failed to connect to consensus node: failed to connect to any beacon node

I tried in versions 1.28.4 (where it worked before) and latest version of1.31.0 (error message slightly different, but it did not work either)

**Comment by mcdee** [comment]
I just checked with a local copy and this works okay, what specific error are you seeing with 1.31.0?

**Comment by jagmot** [comment]
I am trying to create the offline preparation file. It no longer works. 1.31 specific error message

ethdo validator exit --prepare-offline
No connection supplied with --connection parameter and no local beacon node found, attempting to use mainnet fallback
Error: failed to process: failed to connect to any beacon node

ethdo validator credentials set --prepare-offline
No connection supplied with --connection parameter and no local beacon node found, attempting to use mainnet fallback
Error: failed to process: failed to connect to any beacon node

**Comment by jedandroby** [comment]
I am getting the same error when trying to execute the second command. 
![image](https://github.com/wealdtech/ethdo/assets/51110883/c262d259-91de-4e4c-b362-668d0e31f160)

**Comment by mcdee** [comment]
Please try it again and see if it works now.

**Comment by jedandroby** [comment]
Whatever you just did fixed it.  Got the offline prep json! mahalo sir! XD
