### ISSUE TITLE
The latest Windows version seems to be broken

### ISSUE THREAD

**Issue by one-three-three-seven** [wealdtech/ethdo#111]
The releases **1.33.0** and **1.33.1** do always crash with **ERR Init curve=5** on **Windows 11**.

Older versions work fine.

**Comment by remyroy** [comment]
I can confirm this. I'm getting the same issue.

**Comment by remyroy** [comment]
The issue was introduced with release 1.33.0. Looking at [the diff], I'm guessing the issue was introduced with an updated dependency in 1c23e7cc54b1b8daed953efa9de361b1b0f6b89b. I'll try to track which dependency is the source of this.

**Comment by remyroy** [comment]
It seems like the issue is in the `github.com/herumi/bls-eth-go-binary` dependency.

**Comment by remyroy** [comment]
Updating `github.com/herumi/bls-eth-go-binary` to v1.32.1 should fix this issue. See https://github.com/herumi/bls-eth-go-binary/issues/54

**Comment by mcdee** [comment]
Thanks for tracking this down.  Building a new release now.

**Comment by mcdee** [comment]
https://github.com/wealdtech/ethdo/releases/tag/v1.33.2 is now available, please let me know if this addresses the issue.

**Comment by remyroy** [comment]
This latest, v1.33.2, now works on Windows. Thanks.

**Comment by mcdee** [comment]
Thanks again for chasing this down and confirming the fix.
