### ISSUE TITLE
FR: hd wallet accounts sort/index

### ISSUE THREAD

**Issue by MysticRyuujin** [wealdtech/ethdo#12]
The sorting of the accounts seems to be random when you do `ethdo wallet accounts --wallet <wallet_name>`

Which is especially strange when using HD wallets...

When I created 5 accounts under an HD wallet using:
```
ethdo account create --account="prysm/0" ...
ethdo account create --account="prysm/1" ...
ethdo account create --account="prysm/2" ...
ethdo account create --account="prysm/3" ...
ethdo account create --account="prysm/4" ...
```

and then do a list:
`ethdo wallet accounts --wallet prysm`

They come back in a random order:
```
0
4
3
1
2
```

Anyway, just thought it was weird and that might be a UX improvement?

**Comment by mcdee** [comment]
Thanks for the feature request.  The underlying wallet code makes no promises about ordering of returned accounts.  Although ethdo could attempt to order them it would not get it right in all situations (numeric vs alphabetic, for example), and more importantly it would delay the return of wallet information as all would have to be returned before it could display anything.

On balance I think I'm going to leave this as it is, and allows sorting to occur externally if required (_e.g._ `ethdo wallet list | sort -n`)

**Comment by MysticRyuujin** [comment]
I'm not sure I understand how `ethdo wallet list | sort -n` would sort an HD wallet appropriately?

HD wallets are by their very definition ordered, the above would sort by name, not index?

When I use a ledger or other wallets and I load accounts from it, they are presented in HD order.

I accept that you don't want to implement it but I want to make sure I'm being clear here that I don't expect ordering based on names, I would expect ordering of an HD wallet to be, by definition, deterministic.

**Comment by mcdee** [comment]
Sorry, I get it now.

I'll reopen this and have a look at if there is some way of doing this without impacting on non-HD wallets.

**Comment by MysticRyuujin** [comment]
No problem at all...I acknowledge that ethdo operates differently and is based on the existence of files and that accounts can be created or deleted from disk. Now that I think about that particular fact, I can see how implementation would be difficult.

If it's not a reasonable feature to implement don't worry about it.

I would think that an index # or HD path derivative could be used, but as you said you'd have to collect them all first and then sort, though I'm not sure that's all that impactful, as an end user I have to wait for them to all be found anyway 😄

**Comment by mcdee** [comment]
Version 1.5.1 has been released, which sorts the output of "wallet accounts" by path (for HD wallets) or name (for non-HD wallets).  If this doesn't do what is expected, please could you open a new issue with details of where it fails?  Thank you.
