### ISSUE TITLE
go version compat

### ISSUE THREAD

**Issue by kumavis** [wealdtech/ethdo#127]
readme states:
> Note that ethdo requires at least version 1.13 of go to operate. The version of go can be found with go version.

however i got the following error:
```
# github.com/golang/glog
../../go/pkg/mod/github.com/golang/glog@v1.1.1/glog_file_other.go:27:6: abortProcess redeclared in this block
	../../go/pkg/mod/github.com/golang/glog@v1.1.1/glog_file_linux.go:33:6: other declaration of abortProcess
note: module requires Go 1.19
```

does it actually require 1.19?

**Comment by mcdee** [comment]
Yeah looks like the readme is out of date, will update it.
