### ISSUE TITLE
Failed to generate offline-preparation.json

### ISSUE THREAD

**Issue by wslzh1020** [wealdtech/ethdo#128]
![WechatIMG154](https://github.com/wealdtech/ethdo/assets/157975663/38ef0338-877a-494b-a829-b39c4aeaf651)
Error: failed to process: failed to obtain validators: failed to read body: context deadline exceeded

**Comment by mcdee** [comment]
Add `--timeout=30m` to your command, that will give it lots of time to retrieve the file.
