### ISSUE TITLE
Issue with using Windows ENV variables

### ISSUE THREAD

**Issue by MysticRyuujin** [wealdtech/ethdo#13]
```
C:\Users\chase>ethdo version
1.4.21
```
In this image you can see I have configured ETHDO_ variables for BASEDIR, STORE, and STOREPASSPHRASE (I know STORE defaults to filesystem, I added it as a test, because it doesn't work either way)

![image](https://user-images.githubusercontent.com/8877131/85926149-f67e4e80-b862-11ea-9168-24d401dc80bf.png)

Here you can see that if I manually add the same parameters, it works fine, but it isn't reading from the ENV variables, even though they are set...

![image](https://user-images.githubusercontent.com/8877131/85926195-51b04100-b863-11ea-9964-88be99ad37dc.png)

I THINK this was working before / on older versions, I had this configured before, I think...I'm not sure what changed...I could just be doing something totally wrong...?

**Comment by MysticRyuujin** [comment]
I figured it out...

It's now `ETHDO_STORE-PASSPHRASE` but still `ETHDO_BASEDIR`

**Comment by mcdee** [comment]
Thank you for raising the issue.  The variable should be `ETHDO_STORE_PASSPHRASE`, so I'm reopening this for fixing.

**Comment by mcdee** [comment]
Note that with ethdo version 1.5.0 underscores in environment variables should now be consistent, so `ETHDO_STORE_PASSPHRASE` should be used in the example above.

**Comment by MysticRyuujin** [comment]
I think it's still broken...and I'm not sure why...

![image](https://user-images.githubusercontent.com/8877131/88244895-d2900c00-cc5a-11ea-86c6-3f233b942768.png)

**Comment by MysticRyuujin** [comment]
I got it... It's: `ETHDO_BASE_DIR` not `ETHDO_BASEDIR`

Not sure if that's intended?
