### ISSUE TITLE
mnenomics for changing withdrawal credentials

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [wealdtech/ethdo#136]
Hi, i had a question

should i have different mnemonics, when generating validators keys and withdrawal address

or is it recommended to have the SAME mnemonic for both - validator keys and withdrawal credentials?

Please advise

i ask since i have a problem when using ethdo to change withdrawal credentials ..

ethdo **ignores** the first 8 validators, and starts from validator index 8 in the path (the 9th validator), when searching for validators to change the withdrawal credentials of ..

i am stumped and do not understand why is this happening

<img width="835" alt="Screenshot 2024-05-10 at 02 18 17" src="https://github.com/wealdtech/ethdo/assets/30082863/b72e2722-eed2-4c38-9c26-13749f5075fe">

**Comment by mcdee** [comment]
Please can you rerun the command with `--verbose`?  It should show that the first 8 validators are found.

**Comment by SyedMuhamadYasir** [comment]
> Please can you rerun the command with `--verbose`? It should show that the first 8 validators are found.

i did one better, i generated a new set of validators from a fresh BIP-39 mnemonic, with the help of staking-cli and then used ethreal to generate deposit_data and submit deposit for the first 8 validators,

however when i use ethdo to try to change the credentials of the very first validator, i face a different error;

<img width="1646" alt="Screenshot 2024-05-22 at 01 15 33" src="https://github.com/wealdtech/ethdo/assets/30082863/0dae119b-7bda-4249-a41e-52c566d8214c">

please note that this validator is awaiting activation, however, i should still be able to change withdrawal credentials, no?

**Comment by SyedMuhamadYasir** [comment]
i must add that for the specified validator, the withdrawal credentials are NOT "**0x00cb1558c75916f0232548cfd16f79a7fa36e39eb8021625c9d7e4a520b7c4a6"**

but in truth they are;

![image](https://github.com/wealdtech/ethdo/assets/30082863/391ec779-a68f-4d7d-a9b4-c7e85718b14f)

as you can see in the screenshot, they are : **"00f817bee2ba6342e9d3a7418300a22c32657d8331ad920d5fe4bf96f687a2fc"**

so why is ethdo detecting wrong credentials?

**Comment by mcdee** [comment]
`--private-key` in that command is the private key of the _withdrawal_ keypair, as per https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md.  I suspect that you are using the private key of the _validator_ keypair in your example, which is why it does not match.

**Comment by SyedMuhamadYasir** [comment]
> `--private-key` in that command is the private key of the _withdrawal_ keypair, as per https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md. I suspect that you are using the private key of the _validator_ keypair in your example, which is why it does not match.

ok that makes sense,

where / how can i find the private key of the withdrawal keypair? i generated these validators using staking-cli

**Comment by SyedMuhamadYasir** [comment]
i was able to change it with mnemonic!

![image](https://github.com/wealdtech/ethdo/assets/30082863/67d4bbdf-466e-47f2-93dc-d5b1d63bbef6)

BUT i'd like to keep this issue open until i also manage to do some withdrawal credentials change with ethdo account derive!

thanks!

**Comment by SyedMuhamadYasir** [comment]
> If you generated the keys with a mnemonic then the simplest option is to use the same mnemonic to generate the withdrawal credentials change operation. If you explicitly want the withdrawal private key then you need to generate it from the mnemonic with `ethdo account derive`. Details on the path to use are in the document I linked in my previous comment.

this is fantastic, but do we need necessarily need the _path_ ? the tool i used to generate the validators (eth2-val-tools by protolambda) generates empty values for path in the keystores

ofcourse, if the path is an absolute necessity, then i will use staking-cli to generate the validators again

**Comment by mcdee** [comment]
`ethdo account derive` requires a path and mnemonic to provide the correct account details.

**Comment by SyedMuhamadYasir** [comment]
> `ethdo account derive` requires a path and mnemonic to provide the correct account details.

thanks, i will use the staking-cli to generate the **same** validators as i had before and then obtain (derive?) their withdrawal key

**Comment by mcdee** [comment]
The path to your validator key and the path to your withdrawal key are different so you won't see them both with the same command.  Please read the "Using a mnemonic and path" section of the withdrawals credentials doc at https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md#using-a-mnemonic-and-path for details.
