### ISSUE TITLE
documentation for making a deposit through ethdo?

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [wealdtech/ethdo#139]
I am probably not able to see the obvious, but is there a separate documentation for making a validator deposit through ethdo?

i just cant seem to find it ..

**Comment by mcdee** [comment]
`ethdo` is a consensus layer tool.  `ethereal` is an execution layer tool and you can create deposit transactions with that.  https://github.com/wealdtech/ethereal?tab=readme-ov-file#deposit has details on how to do this once you have used `ethdo` to create deposit data.
