### ISSUE TITLE
withdraw balance from exited validator without changing credentials

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [wealdtech/ethdo#145]
![image](https://github.com/user-attachments/assets/6d489043-257f-4d1e-8a46-28392c57b95d)

As you can see, i exited a validator using ethdo,

however, the balance has still not been credited to any wallet, i was thinking that the wallet that submitted the stake balance would simply get back the withdrawn balance

this has not happened

so can you please guide on what to do here

**Comment by mcdee** [comment]
Your withdrawal credentials are not set to an execution address, so there is nowhere to send the balance.

Details on using ethdo to change the withdrawal credentials can be found at https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md

**Comment by SyedMuhamadYasir** [comment]
> Your withdrawal credentials are not set to an execution address, so there is nowhere to send the balance.
> 
> Details on using ethdo to change the withdrawal credentials can be found at https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md

i see, can we still change the withdrawal credentials of a validator which is in the `withdrawal_possible` state?

**Comment by mcdee** [comment]
> i see, can we still change the withdrawal credentials of a validator which is in the `withdrawal_possible` state?

Yes.
