### ISSUE TITLE
Create multiple validator keys

### ISSUE THREAD

**Issue by 0xDones** [wealdtech/ethdo#146]
### Description

Is there an easy way to create multiple validator keys, similar to `staking-deposit-cli` where I can specify the `--num_validators` argument?

**Comment by mcdee** [comment]
Not directly, but it would be easy enough to create multiple accounts within a shell, for example:

```bash
for i in $(seq 1 100)
do
  ethdo account create --account=Validators/${i} --passphrase=${PASSPHRASE}
done
```

**Comment by 0xDones** [comment]
Thanks @mcdee
