### ISSUE TITLE
ethdo signature verify --signer: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MrTickl3** [wealdtech/ethdo#148]
Hello,
I used Version 1.36.0 to create a new Wallet, imported 3 keystore.json accounts and successfully signed the same message/data with each of them.
The verification with `ethdo signature verify --data="..." --signature="..." --account="Wallet/Account"` works, however not, when using `--signer="..."` instead of `--account="Wallet/Account"`

It produces the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf89d11]

goroutine 1 [running]:
github.com/wealdtech/ethdo/cmd.init.func27(0x21731c0?, {0x1353ac3?, 0x4?, 0x1353ac7?})
	/home/runner/work/ethdo/ethdo/cmd/signatureverify.go:76 +0x491
github.com/spf13/cobra.(*Command).execute(0x21731c0, {0xc000656c90, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x2172640)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/wealdtech/ethdo/cmd.Execute()
	/home/runner/work/ethdo/ethdo/cmd/root.go:123 +0x1a
main.main()
	/home/runner/work/ethdo/ethdo/main.go:19 +0xf

```
System is Ubuntu 22.04 LTS AMD64. What further information can I provide to you?

**Comment by mcdee** [comment]
Thank you for reporting this issue.  It has been addressed in 7d00d1261f487b830d8b196bc1a26ddef9c1d6e5 and will be available in a future release.
