### ISSUE TITLE
`ethdo wallet create` not recognizing `--basedir`

### ISSUE THREAD

**Issue by djrtwo** [wealdtech/ethdo#15]
`ethdo wallet create` is silently not recognizing `--basedir` input on my macos and instead reverting to the default.

I haven't had a chance to debug but wanted to drop it here for visibility

**Comment by mcdee** [comment]
Thanks for reporting this.  Do you see this issue with both wallet types (hierarchical deterministic and non-deterministic) or just one?

**Comment by djrtwo** [comment]
Originally found with non-deterministic, but double checked and is the case for hierarchical deterministic as well

**Comment by mcdee** [comment]
Thanks; working on an update that will include a fix for this.

**Comment by mcdee** [comment]
Version 1.5.0 has been released, which should address this issue.  Please give it a go and re-open the issue it appears that the issue has not been resolved with this release.
