### ISSUE TITLE
Version not bumped

### ISSUE THREAD

**Issue by MysticRyuujin** [wealdtech/ethdo#16]
The latest docker is tagged `1.4.22` and current tags on github are showing `1.4.22` but `ethdo version` is still `1.4.21`

**Comment by mcdee** [comment]
Thank you for reporting this.  `ethdo` now uses dynamic versioning, where the version is built in to the release based on its tag, so this should no longer be a problem.  If you see this happening again past release 1.5.0 please open a new issue.

**Comment by MysticRyuujin** [comment]
I think this is still broken. Release version is `1.5.9` but `ethdo version` still reports `1.5.8` and this suggests it's static from a string:

https://github.com/wealdtech/ethdo/blob/master/cmd/version.go#L25

**Comment by MysticRyuujin** [comment]
1.6.2 / 1.6.1 is the same
