### ISSUE TITLE
Can't Create Accounts in v1.5.5

### ISSUE THREAD

**Issue by dsystems-io** [wealdtech/ethdo#19]
Just upgraded to latest version and I can no longer create new accounts on existing wallets, nor newly created wallets. Been using these functions in previous versions up to 1.5.2

### Environment
Ubuntu 18.04
Golang 1.14.4
Ethdo 1.5.5

### Steps to Reproduce
```shell
ethdo wallet create --wallet="Validators"
ethdo account create --account="Validators/test" --passphrase="1234"
```
Results in

`Failed to access wallet: invalid account format`

**Comment by mcdee** [comment]
Thank you for reporting this issue.  This has been addressed in v1.5.6.  If you continue to be unable to create accounts after upgrading please reopen this issue with details.
