### ISSUE TITLE
Add Support for RAW Deposit Data Verification

### ISSUE THREAD

**Issue by dsystems-io** [wealdtech/ethdo#20]
Currently the `deposit verify` command accepts either 1) JSON or 2) JSON file. However, the `validator depositData` command also outputs RAW data. Is it possible for the  `deposit verify` command to also validate the RAW format data as well?

**Comment by mcdee** [comment]
Thank you for raising this feature request.  Version 1.5.8 of `ethdo` now supports receiving the raw transaction hex string in the `--data` field.  Please reopen this issue if it fails to work as expected.
