### ISSUE TITLE
Export to EIP2335 spec keystore

### ISSUE THREAD

**Issue by OisinKyne** [wealdtech/ethdo#21]
Hi there,

I know a lot of key management is in flux at the moment with respect to Eth2 and ethdo, I'm just wondering if there are plans  for exporting ND accounts/private keys in the [EIP2335](https://eips.ethereum.org/EIPS/eip-2335) format?

From talking to the Prysm team, currently the best way to make prysm work with ethdo generated wallets is to make a HD wallet on ethdo with a custom derivation path in the form prysm expects (`m/12381/3600/i/0/0`), and then use `prysm wallet-v2 recover` with the mnemonic and it will assume the derivation path of each sub account. 

I am using ethdo to create validating keys only, and as such, ND accounts with password protection seemed the most convenient way for me to create and manage these wallets rather than mnemonics. In a perfect world, I would use ethdo to generate a ND account, use it to generate deposit data for this account with a supplied withdrawal pub key, and then subsequently load the ND account into a prysm validator with the passphrase and off I go (assuming I can do that with EIP2335 format keystore files). Is this something that is feasible/planned or should I be going down the HD route of creating wallets and importing them via mnemonic?

**Comment by mcdee** [comment]
ethdo writes keystores in EIP-2335 format (with an additional field `name`) so they should be usable by prysm.  Is there a specific problem with using them?

**Comment by OisinKyne** [comment]
My bad, I just saw the hex output and no mention of EIP2335 so I assumed it used something different, I was expecting to find JSON that looked something like:

```json
{
    "crypto": {
        "kdf": {
            "function": "pbkdf2",
            "params": {
                "dklen": 32,
                "c": 262144,
                "prf": "hmac-sha256",
                "salt": "d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
            },
            "message": ""
        },
        "checksum": {
            "function": "sha256",
            "params": {},
            "message": "8a9f5d9912ed7e75ea794bc5a89bca5f193721d30868ade6f73043c6ea6febf1"
        },
        "cipher": {
            "function": "aes-128-ctr",
            "params": {
                "iv": "264daa3f303d7259501c93d997d84fe6"
            },
            "message": "cee03fde2af33149775b7223e7845e4fb2c8ae1792e5f99fe9ecf474cc8c16ad"
        }
    },
    "description": "This is a test keystore that uses PBKDF2 to secure the secret.",
    "pubkey": "9612d7a727c9d0a22e185a1c768478dfe919cada9266988cb32359c11f2b7b27f4ae4040902382ae2910c15e2b420d07",
    "path": "m/12381/60/0/0",
    "uuid": "64625def-3331-4eea-ab6f-782f3ed16a83",
    "version": 4
}
```

But I never played around with decoding the hex export in any way or maybe I might have figured this out. Will close, thanks for the help.

**Comment by OisinKyne** [comment]
In case anyone finds this comment. This is how I got an ND ethdo wallet into Prysm Accounts V2 using the docker versions of both, you don't have to `export` the account from ethdo, prysm can import the files from ethdo as they are on-disk once you supply the account password to prysm. Thanks for the help @mcdee 

CC @rauljordan as you've been working on a V2 ethdo support docs. 

```bash
docker run -v /mnt/disk/:/data -e ETHDO_PASSPHRASE="password-here" wealdtech/ethdo --basedir=/data wallet info --wallet=Validator --verbose

```
Grab the path from the 4th line of the output `Location: ` and put it into the next command for prysm
```bash

docker run -v /mnt/disk0/:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest accounts-v2 import --wallet-dir=/data --wallet-password-file=/data/prysm/validator-password --keys-dir=$LOCATION --account-password-file=/data/prysm/validator-password

```
