### ISSUE TITLE
Where is the doc kept for the summary capabilities of ethdo, and for how to use the tool?

### ISSUE THREAD

**Issue by A2be** [wealdtech/ethdo#23]
I'm a Github noob, and work at a non-technical level, but still need the seed phrase resolution services that made @benjaminion recommend your tool so wholeheartedly.

Would be cool if I could find on the Github front page where to go for this info.  (I checked the wiki, and it was empty.)

Thanks.

**Comment by mcdee** [comment]
https://github.com/wealdtech/ethdo/#howto provides a link to the document that discusses conversions from mnemonics to keys.
