### ISSUE TITLE
pyrmont and --launchpad switch

### ISSUE THREAD

**Issue by slayorktc** [wealdtech/ethdo#27]
On version 1.7.0 I ran this:

./ethdo validator depositdata --withdrawalaccount="Staking Wallet/withdrawel0" --validatoraccount="Staking Wallet/validator0" --depositvalue=32Ether --passphrase="mypass" --launchpad --forkversion=0x00002009

I pasted the output this into a file called upload.json
[{"pubkey":"afd7aa0438d1db0d9d2f692c5aa7533a8a136da7971d7eee28cd29706e19dfdb5e5ef86e9127fa7e5f863dab6eb78eb1","withdrawal_credentials":"00c3af365daab1416183c616dcb6125562c40b033f49e721570d4150186929ac","amount":32000000000,"signature":"b05e369be6e463ae9aafdbcc751dbf8e4763380c2a91fefa9f9013cf6004de285a28d15e77a2383e2155414a7df85cd9164f949af424d637851f530ffb550144dc263f1d1830cc40e391dd9af6d7eebea9c49091fb9277157154ad288df491c8","deposit_message_root":"d5789c6c8c36c49d6ea4d9f31788ed26628eb0154db6a3698b0dc8bdcaf9e156","deposit_data_root":"2a8184ec35b8f1b81e2de52bc28d583e49cadbf7517f9dba608abcb97967752a","fork_version":"00002009"}]

I tried to upload this json on this website:

https://pyrmont.launchpad.ethereum.org/upload-validator

I got this message

Oops! The json file you provided isn't for the Pyrmont testnet

**Comment by slayorktc** [comment]
Got it working by manually adding this to the end of the json

"eth2_network_name": "pyrmont", "deposit_cli_version": "1.1.0"

The --launchpad switch should be updated to add it.

**Comment by slayorktc** [comment]
ethdo doesn't generate correct data for mainnet launchpad either.

**Comment by mcdee** [comment]
Version 1.7.3 of ethdo should generate launchpad deposit data with this information present.
