### ISSUE TITLE
`validator depositdata --depositvalue` input not reflected in the output

### ISSUE THREAD

**Issue by BisonDee** [wealdtech/ethdo#28]
When using the command `ethdo validator depositdata --depositvalue 32000000000000000000` the resulting JSON returns a the following
```json
[
   {
      ...
      "amount":32000000000,
      ...
   }
]
```
Is this expected?

**Comment by BisonDee** [comment]
When using this output with the `ethereal` tool, it appears that this value is not used anyway because the value/amount of the deposit is explicitly specified.

```
DEPOSITDATA=$(cat ./deposit-data-formatted.json)

ethereal beacon deposit \
      --network=goerli \
      --eth2network=pyrmont \
      --data="$DEPOSITDATA" \
      --privatekey=$PRIVKEY \
      --from=$FROM \
      --value="32 Ether"
```

**Comment by mcdee** [comment]
The `amount` field in the deposit data is in Gwei, whereas amounts specified on the command line are in human-readable format _e..g_ `32 Ether`, hence the apparent discrepancy.

The `--value` in the `beacon deposit` command is ignored; I will see if I can hide the flag for that command.

**Comment by BisonDee** [comment]
Thanks Jim. My primary concern was that an input of `32000000000000000000` (in Gwei) does not have the same value as the output in JSON for the amount which is `32000000000`.

**Comment by mcdee** [comment]
The input isn't in gwei, it's in wei.  Ethereal is written for Ethereum 1, and the idea of using Gwei as a base unit didn't come around until Ethereum 2.

**Comment by BisonDee** [comment]
Thank you for explaining this. This makes sense now.
