### ISSUE TITLE
Panic when "ethdo chain status"

### ISSUE THREAD

**Issue by handelaar2** [wealdtech/ethdo#35]
Ran the command `ethdo --connection=localhost:4000 chain status` which resulted in a dump.
It says: "missing method finality"

On the other hand `ethdo --connection=localhost:4000 chain info` works correctly.
The beacon behind this is Prysm setup as nocturne

<img width="708" alt="2021-05-13_12-45-40" src="https://user-images.githubusercontent.com/28559038/118117657-35ba7d00-b3ec-11eb-9b78-9b62f8539e14.png">

**Comment by mcdee** [comment]
Thanks for reporting this.  The prysm native API does not support all required functions, and it is not yet conformant with the standard API, so the functionality is not available.  However ethdo should exit cleanly in such situations; I'll update the code to handle this.

**Comment by mcdee** [comment]
Addressed in release 1.9.1
