### ISSUE TITLE
Separation of keys between testnets

### ISSUE THREAD

**Issue by paulhauner** [wealdtech/ethdo#4]
I've said it before, but I like to start first issues with a thanks to the developers. So, thanks for creating this project and starting the effort to standardize wallets.

Something I've been considering is separating keys between testnets. For example, Geth maintains a separate `goerli/keystore` dir so you don't mix up mainnet and testnet keys. I've found this to be generally pretty useful.

Whilst I haven't done anything on the Lighthouse side to achieve this, it's one of those lingering todos. I'm interested to hear your thoughts on if segregation of testnets is necessary and how we might go about it.

**Comment by mcdee** [comment]
Personally I use different wallet names, _e.g._:

```
$ ethdo wallet list
Schlesi validators
Topaz validators
Staking
```

(In this case I'm using a single wallet 'Staking' for withdrawal keys across all testnet wallets).

My thinking was that creating completely separate locations for different test networks can be artificial.  I share some keys between the Ethereum 1 testnest, for example, and at current have to do so by copying them from one directory to another.  Wallet names allow users to choose how best to separate out their keys without putting arbitrary restrictions on their locations.

Does this provide enough separation for you, or are you looking for something additional?

**Comment by paulhauner** [comment]
> Does this provide enough separation for you, or are you looking for something additional?

I think this is fine. We also allow for a `--base-dir` flag so you can use a completely isolated set of wallets if you wish.

Happy for you to close this if you want, I was just keen to hear your thoughts :)

**Comment by mcdee** [comment]
Cool.  The underlying wallet code behind `ethdo` does allow for a base directory as well, although I haven't implemented it for `ethdo` itself.  I'll keep this open if I may, to remind myself to add this flag.
