### ISSUE TITLE
[Feature] As a user, I would like the verify command also validating the signature with BLS

### ISSUE THREAD

**Issue by leckylao** [wealdtech/ethdo#42]
This is the validate deposit on the official CLI, so would be including something like that. 

https://github.com/ethereum/staking-deposit-cli/blob/e2a7c942408f7fc446b889097f176238e4a10a76/staking_deposit/utils/validation.py#L85

**Comment by mcdee** [comment]
Fixed in https://github.com/wealdtech/ethdo/commit/4977ee82e5c89092547a71dfd6a68f67aade1b31
