### ISSUE TITLE
Supplied deposit_message_root is not verified

### ISSUE THREAD

**Issue by aaron-alderman** [wealdtech/ethdo#43]
In the latest release (1.25.0), there is now a check to ensure the BLS signature is valid based on the supplied deposit data, however, there is no check to ensure the `deposit_message_root` provided by the user is the same as the generated `depositMessageRoot` here: https://github.com/wealdtech/ethdo/blob/master/cmd/depositverify.go#L273

Adding a check would ensure any accidental modification of the deposit data is caught.

**Comment by mcdee** [comment]
Thank you for this issue and related contribution; it has been merged.
