### ISSUE TITLE
BLS withdrawal derivation key "search" constraint

### ISSUE THREAD

**Issue by mrabino1** [wealdtech/ethdo#51]
Based on the docs, if a staker wants to migrate all of the validators to one unified EL ETH address, the docs outline that ethdo will search for all used keys based on the 24 seed phrase. Out of curiosity, how far (e.g. how many derivations) will ethdo try before it determines there are no more? 10? 100? 1000? more? thx.

**Comment by mcdee** [comment]
[Apologies I missed this issue somehow.]

It goes up to 1,024 validators after the last one that was found, so if for example you had a validator at index 1,000 it would scan up to index 2,024 before it stopped looking.  This should allow for most patterns of usage.

**Comment by mrabino1** [comment]
Excellent UX and well thought out. a thank you !
