### ISSUE TITLE
Offline bls to execution change workflow...

### ISSUE THREAD

**Issue by rolfyone** [wealdtech/ethdo#52]
Currently, if we are offline signing and then submitting validator withdrawal credential changes, it is possible to do the entire flow with no confirmation or warning...

 - validator credentials set --offline-preparation
 - validator credentials set --offline
 will create the change-operations.json file

Then the user can post that directly to their beacon-api for submitting the changes.

It'd be nice if during --offline, a warning can be given prior to signing. Ideally its an actual prompt that can be turned off with `--yes` or something for script users...

The reason I think this is important, is once this operation is complete, it can't be changed again. It would help us at least ensure the user knew that it couldn't be undone before they go and submit their change and do something really permanent...

Prior to signing is the best place to put this, as once the message is signed and in the correct file format, it can be submitted directly with no other tools we control.

so I guess, the user does
```
validator credentials set --offline

WARNING: Updating validator credentials to an eth address is permanent and cannot be changed again once this operation completes. Are you sure that the above is correct?
```
I'd be very tempted to force them to type YES all in caps to proceed so they don't automatically go 'y' and ignore it...

**Comment by lastperson** [comment]
It would also be nice to mention that before the Capella fork, the credentials set will not have effect on the consensus layer state, and the operation will stay on a single node without further effects until the fork.

**Comment by mcdee** [comment]
Thanks for raising this.  `ethdo` isn't built for interactive use, the design is very much for the user to provide all of the parameters required on the command line and let the tool do its job.  With the advent of the staking deposit CLI and wagyu both available to carry out more interactive credentials change operation walkthroughs, I'm going to close this rather than go down the interactive path.
