### ISSUE TITLE
[Feature Request] Shard an existing key into multiple shares

### ISSUE THREAD

**Issue by ThomasDalla** [wealdtech/ethdo#60]
Distributed validator technology (DVT) solutions such as [SSV](https://docs.ssv.network/developers/tools/ssv-key-distributor) and [Obol](https://github.com/ObolNetwork/charon-distributed-validator-cluster#import-existing-validator-keys) offer the possibility to shard an existing key (an account from an hd wallet) into multiple shares (that they then distribute amongst different "operators").
`Nimbus` is also offering a similar solution (not production ready) to split a keystore and store shares in separate instances of `web3signer`: https://github.com/status-im/nimbus-eth2/blob/b564ddd2f95f68f53692482199a2abaa5963376e/docs/the_nimbus_book/src/web3-signer.md#distributed-keystores

The outcome is similar to a remote `ethdo` wallet distributed across multiple instances, but comes with a lot more custom infrastructure to adopt (SSV token for example).

Having a similar built-in feature in `ethdo` directly would enhance all applications that leverage ethdo (such as `dirk`) to offer similar benefits to the native distributed wallet, but from existing "standard" hd wallets.\
There are many cases were only hd wallets are supported (for example the keys generated by the `RocketPool` CLI) so offering built-in support to split them within `ethdo` could greatly improve the resilience of these use cases.

_Original request under dirk's github: https://github.com/attestantio/dirk/issues/30_

**Comment by ybstaked** [comment]
Very interested in this feature being available!

**Comment by selfuryon** [comment]
We created app called `DKC`: https://github.com/p2p-org/dkc - dirk key converter. In several days, we also add a possibility to convert directly from/to keystores.

Now you can convert ND Wallets and Distributed Wallets in both direction.
