### ISSUE TITLE
[BUG] GET failed with status 429: {"message":"grpc: received message larger than max (70716954 vs. 4194304)

### ISSUE THREAD

**Issue by jeffersonwarrior** [wealdtech/ethdo#62]
When trying to generate an offline file, I get a 429 error with this command

./ethdo validator credentials set --prepare-offline --connection (eth2 beacon node:3500)

**Comment by jeffersonwarrior** [comment]
Update: this seems to be an issue with eth2 client...Posted there -- gRPC max receive size option needs to be set.

https://github.com/attestantio/go-eth2-client/issues/44

**Comment by mcdee** [comment]
This is an option that needs to be set on the prysm beacon node.

**Comment by jeffersonwarrior** [comment]
I did set on the prysm beacon node.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jeffersonwarrior** [comment]
Hello,

I added as specified and restarted.

/home/eth2/prysm/prysm.sh beacon-chain  --execution-endpoint=http://x.x.x.x:8551 --grpc-gateway-host x.x.x.x --grpc-gateway-port 3500 --rpc-host x.x.x.x --rpc-port 4000 --jwt-secret /home/eth2/nethermind/keystore/jwt-secret --suggested-fee-recipient=xxxxxx--http-mev-relay ***@***.*** -p2p-max-peers 100 --monitoring-host x.x.x.x --monitoring-port 8080 --rpc-max-page-size=200000 --grpc-max-msg-size=268435456

I receive the same error message:

Connections to remote beacon nodes should be secure.  This warning can be silenced with --allow-insecure-connections
Error: failed to process: failed to obtain validators: failed to request validators: GET failed with status 429: {"message":"grpc: received message larger than max (70727532 vs. 4194304)","code":429}

From: Jim McDonald ***@***.***>
Date: Saturday, February 11, 2023 at 12:18 PM
To: wealdtech/ethdo ***@***.***>
Cc: Jefferson Nunn ***@***.***>, Author ***@***.***>
Subject: Re: [wealdtech/ethdo] [BUG] GET failed with status 429: {"message":"grpc: received message larger than max (70716954 vs. 4194304) (Issue #62)

Try adding --rpc-max-page-size=200000 --grpc-max-msg-size=268435456 to your prysm beacon node.

**Comment by mcdee** [comment]
Either the restart didn't take place, or you are pointing to a different server, or perhaps your command line is incorrect (there are a couple of issues in the command line you pasted but they may be due to you changing some of the values).

`ethdo` talks to the beacon node's REST API.  In prysm, the REST API is a frontend for their GRPC interface which is what is throwing the errors.

You can check prysm's command line with `ps -elf | grep prysm` and see if the updated parameters are there.  You can also check the prysm log for `Starting beacon chain with max RPC page size of 200000`

**Comment by jeffersonwarrior** [comment]
Turns out the wrong file was being edited. Now I have a new error message

From Prysm
2023/02/11 13:56:31 http: superfluous response.WriteHeader call from github.com/prysmaticlabs/prysm/v3/api/gateway/apimiddleware.WriteError (process_request.go:264)
time="2023-02-11 13:56:31" level=error msg="Could not write error message" error="http: wrote more than the declared Content-Length" prefix=apimiddleware
time="2023-02-11 13:56:36" level=info msg

From the command line
Connections to remote beacon nodes should be secure.  This warning can be silenced with --allow-insecure-connections
Error: failed to process: failed to obtain validators: failed to request validators: failed to call GET endpoint: Get http://x.x.x.x:3500/eth/v1/beacon/states/head/validators<http://192.168.100.78:3500/eth/v1/beacon/states/head/validators>: context deadline exceeded

From: Jim McDonald ***@***.***>
Date: Saturday, February 11, 2023 at 1:43 PM
To: wealdtech/ethdo ***@***.***>
Cc: Jefferson Nunn ***@***.***>, Author ***@***.***>
Subject: Re: [wealdtech/ethdo] [BUG] GET failed with status 429: {"message":"grpc: received message larger than max (70716954 vs. 4194304) (Issue #62)

Either the restart didn't take place, or you are pointing to a different server, or perhaps your command line is incorrect (there are a couple of issues in the command line you pasted but they may be due to you changing some of the values).

ethdo talks to the beacon node's REST API. In prysm, the REST API is a frontend for their GRPC interface which is what is throwing the errors.

You can check prysm's command line with ps -elf | grep prysm and see if the updated parameters are there. You can also check the prysm log for Starting beacon chain with max RPC page size of 200000

**Comment by mcdee** [comment]
It shouldn't be taking that long to send the data, unless you're going over a low bandwidth connection.  But you can increase the `ethdo` command timeout by adding `--timeout=5m` (which will take the timeout to 5 minutes).

**Comment by jeffersonwarrior** [comment]
That did it. Thanks again.
