### ISSUE TITLE
Stuck on "BLS credentials" after broadcasting change

### ISSUE THREAD

**Issue by 399iejijw9e29ejiwjljasd** [wealdtech/ethdo#65]
OS: Windows
Client: Prysm v3.2.1
Geth: 1.11.1-stable
ethdo: 1.28.1

I configured my Pyrsm client with the --grpc-max-msg-size 268435456 and followed all the steps for an offline change. Everything executed successfully. When I run 

X:\ethdo>ethdo validator credentials get --validator=XXXX
BLS credentials: 0x00...

It's been like this for about 7-8 hours. The documentation reads:

"If the result starts with the phrase "BLS credentials" then it may be that the operation has yet to be incorporated on the chain, please wait a few minutes and check again. If this continues to be the case please obtain help to understand why the change operation failed to work."

However there are no details beyond that and nothing in the troubleshooting section. Not sure what happened or if I should wait longer.

**Comment by 399iejijw9e29ejiwjljasd** [comment]
Oh boy, I didn't see that anywhere in the documentation and it was run on mainnet. What are the implications for running this on mainnet?

**Comment by mcdee** [comment]
Nothing; the message will be rejected (you should have seen this message when sending the change operation with "ethdo validator credentials set").

**Comment by 399iejijw9e29ejiwjljasd** [comment]
It completed with no output.

**Comment by mcdee** [comment]
Did your `credentials-changes.json` file have any data in it?  It may be that no operations were created to broadcast, for some reason.

**Comment by 399iejijw9e29ejiwjljasd** [comment]
Yes, it had data with my wallet, sig, etc.

**Comment by Piradoxlanieve** [comment]
@mcdee  thanks for your job.
so as not to open another thread and I think my question is related.
I have executed the address change in zhejiang perfectly. So:
My doubt is the following: If I execute this in Goerli or mainet, nothing happens and it is rejected, but.... is there a way to leave the order in the queue and when the change to Shanghai is made it is executed automatically in case the mnemonic was compromised?
I hope you can understand my English is bad.
`./ethdo  validator credentials set --mnemonic=" seeed  xxxxxxxxxxxxxxxxx"  --withdrawal-address=0x1xxxxxxxxxxxxxxxxxx  `
