### ISSUE TITLE
Error of change withdraw address command

### ISSUE THREAD

**Issue by dongri** [wealdtech/ethdo#68]
https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md
I tried following this manual, but got the following error
```
$ ethdo validator credentials set
Error: failed to process: failed to submit BLS to execution change: POST failed with status 405: {"code":405,"message":"METHOD_NOT_ALLOWED","stacktraces":[]}
```

Using lighthouse

**Comment by mcdee** [comment]
At current the only networks that accept these credentials change operations are zhejiang and sepolia.  Dates for goerli and mainnet will be announced at https://blog.ethereum.org/ and you will need to upgrade your beacon node prior to submitting your change operation.
