### ISSUE TITLE
Cannot find mnemonic after `wallet create`

### ISSUE THREAD

**Issue by pablomendezroyo** [wealdtech/ethdo#70]
I was looking for a non-interactive tool to create Eth2 wallets. The official [deposit-cli](https://github.com/ethereum/staking-deposit-cli) does not support non-interactive usage so I end up here.

I created a new wallet with
```
./ethdo wallet create --wallet=test --type=non-deterministic --wallet-passphrase=test
```

The resulting files were (none of them containing the mnemonic)
```
8f2caac6-c0d4-4e40-9273-029e67b76f80  index
```

I expected within the resulting files to be the `mnemonic` of the wallet, what am I missing here?

Thanks in advanced!

**Comment by mcdee** [comment]
Non-deterministic wallets don't have mnemonics.  If you want a mnemonic then use `--type=hd` for a hierarchical deterministic wallet.

**Comment by pablomendezroyo** [comment]
@mcdee thankyou! last question, is it possible to set the withdrawal credential Ethereum address at the time of creating the wallet?

**Comment by mcdee** [comment]
Withdrawal credentials aren't related to wallets.  You can set withdrawal credentials for individual validators when creating validator deposit data; see the output of `ethdo validator depositdata --help` for details.
