### ISSUE TITLE
Exit verify failed

### ISSUE THREAD

**Issue by RayLvv** [wealdtech/ethdo#76]
I tried to verify my signature generated by `validator exit` command with `--json` flag, but it failed with following output:
`Failed to obtain exit data: data is not valid JSON: exit missing`
It seems that the json generated doesn't match.

**Comment by RayLvv** [comment]
By the way, may I broadcast my exit message in any epoch after it generated if I don't specify any epoch with `--epoch` flag?

**Comment by mcdee** [comment]
Exactly what commands did you use to generate and verify the exit?  Please paste them in to the issue (removing any identifying information if required).

**Comment by RayLvv** [comment]
> 

I generate the exit message by
 `./ethdo validator exit --validator [keystore.json] --connection [url] --passphrase [secret] --json`
command, and the output seems like this:
`{"message":{"epoch":"166906","validator_index":"index"},"signature":"signature"}`
Verify by this command:
`./ethdo exit verify --exit=../lido-validators/exitSignature.json --pubkey=[pubKey]`
It seems that if I add `exit` and `fork_version` to the output json it can be correct.

**Comment by mcdee** [comment]
Looks like `exit verify` wasn't updated with the new format of `validator exit`, will look to fix this.

**Comment by mcdee** [comment]
This should now work in the latest release. Note they operation parameters have changed, so you would run `./ethdo exit verify --signed-operation=../lido-validators/exitSignature.json`

Please reopen this issue if you continue to have problems; thank you.
