### ISSUE TITLE
Unable to get address for account

### ISSUE THREAD

**Issue by fireduck64** [wealdtech/ethdo#77]
I was trying to use ethdo for something it probably wasn't designed for, namely to derive seeds that I have and give me their ethereum addresses.  I could not manage to do this thing that it is not designed for.  There is probably good reason for this.  If you show users addresses they will send funds to those addresses and if it isn't an expected derivation path that probably won't work out well for them.

**Comment by mcdee** [comment]
`ethdo` is a tool for the Ethereum consensus layer, and as such does not provide Ethereum addresses.
