### ISSUE TITLE
Add BLS to ETH1 change request

### ISSUE THREAD

**Issue by ksheni56** [wealdtech/ethdo#79]
Hello, can I ask why ethdo doesn't support 1 click change bls with ledger?

Thank you.

Regarding to: https://github.com/LedgerHQ/app-ethereum/issues/416

**Comment by mcdee** [comment]
Ledger does not support BLS signing, as per the issue you linked, so it is not possible to use a ledger to create a credentials change operation.

**Comment by mcdee** [comment]
There has been no documentation posted on this, and even though we have communicated directly with Ledger on this we have had no response, so nothing we can work with.

**Comment by ksheni56** [comment]
Okay, that's very unfortunate that your team didn't get a response to share your synergies. I appreciate your feedback and will link our convo to the Ledger support ticket, may be adrienlacombe-ledger could let the team know internally :). So one more question to my topic: Would it be technically possible from your side to integrate that if the implementation of BLS signatures to the ETH app is released?

**Comment by mcdee** [comment]
> Would it be technically possible from your side to integrate that if the implementation of BLS signatures to the ETH app is released?

Impossible to say without seeing the specific APIs.  Work in the past seems to have focused on web apps rather than command line, or requiring integration with third party software (e.g. ledger live), but if there are workable examples for integration from the command line across multiple operating systems it should be possible.  However, it may not be a priority for us given that most uses of the prior functionality came from other staking service providers.

**Comment by ksheni56** [comment]
Thank you very much for sharing details. Yes indeed, this should be the part from the Staking-providers. The Founder from Allnodes told me that he will release a one click workaround for change right after Ledger release their solution. So that I'll pass this to the LedgerHQ topic now, maybe it will go better for the future with the communiaction. :)

**Comment by jmspinelli** [comment]
I guess my confusion stems around the initial operation related to the deposit of the ETH to the validator.  If a Ledger was used to sign the transaction initially with a BLS signature, how is the same operation not possible from a Ledger for this address conversion step?

**Comment by ksheni56** [comment]
I do not know exactly but I suspect because the BLSToExecutionChange is not supported yet?
