### ISSUE TITLE
Error: failed to process: failed to connect to consensus node: failed to connect to any beacon node

### ISSUE THREAD

**Issue by phpmac** [wealdtech/ethdo#80]
It was fine before, but now it prompts this, is there any way to debug, the network is normal.

**Comment by mcdee** [comment]
What command are you running?

**Comment by phpmac** [comment]
> What command are you running?

./ethdo validator credentials get --validator=111

**Comment by mcdee** [comment]
Are you running a local beacon node, and if so is it providing the HTTP REST API?

**Comment by phpmac** [comment]
> Are you running a local beacon node, and if so is it providing the HTTP REST API?

No running node, prompt to use public node

**Comment by phpmac** [comment]
```
```

**Comment by phpmac** [comment]
```
$./ethdo validator credentials set
No connection supplied; using mainnet public access endpoint
$./ethdo validator credentials get --validator=25895
Error: failed to process: failed to connect to consensus node: failed to connect to any beacon node
```

**Comment by phpmac** [comment]
> Are you running a local beacon node, and if so is it providing the HTTP REST API?

That's why, the first few days were normal

**Comment by phpmac** [comment]
> Are you running a local beacon node, and if so is it providing the HTTP REST API?

This error will be prompted when I do not build a local node, no matter any device, any location, any network

**Comment by mcdee** [comment]
For mainnet you can add `--connection=http://mainnet-consensus.attestant.io'  I will look to add this as a default.

**Comment by phpmac** [comment]
> For mainnet you can add `--connection=http://mainnet-consensus.attestant.io' I will look to add this as a default.

Error: failed to process: failed to connect to beacon node: failed to confirm node connection: failed to fetch genesis: failed to obtain genesis

**Comment by phpmac** [comment]
> For mainnet you can add `--connection=http://mainnet-consensus.attestant.io' I will look to add this as a default.

Will he affect my withdrawal?I'm so worried, please help me

**Comment by mcdee** [comment]
The change of credentials operation wont' be affected.  I have reset the server, try it again.

**Comment by phpmac** [comment]
> The change of credentials operation wont' be affected. I have reset the server, try it again.

Still the same

**Comment by phpmac** [comment]
> The change of credentials operation wont' be affected. I have reset the server, try it again.

When using http is normal, when using https is not normal
