### ISSUE TITLE
VEM Online generation - Issue with keystore passphrases with "$" or "!" 

### ISSUE THREAD

**Issue by Calixte13** [wealdtech/ethdo#81]
Running TEKU / GETH, generated Keystores using the staking deposit CLI.

Tried to generate VEM using below guide and "ONLINE only" part. Generating the offline-preparation.json on the online machine.

https://mirror.xyz/ladislaus.eth/wmoBbUBes2Wp1_6DvP6slPabkyujSU7MZOFOC3QpErs

When trying to generate the exit-preparation.json on keystores with passphrase starting with a "$", with a "$" midway and ending with a "!", keep on failing to unlock the account.

Tried to regenerate the keystore files with a simpler passphrase (without $ or !), it worked like a charm.

Command line that failed : 
sudo ./ethdo validator exit --validator=/home/user/ethdo_folder/keystore_0.json --passphrase=$xxxx$xxxx! (27 characters in total) --offline

Command line that suceeded :
sudo ./ethdo validator exit --validator=/home/user/ethdo_folder/keystore_0.json --passphrase=xxxxXxxx00 (16 characters in total) --offline

Tried with a not renamed file, renamed file, with simpler passphrase both worked. Checked authorizations also.

Edit: I did few extra tests to confirm the bug and be more accurate. I generated the test keystore files using the same mnemonic for the 5 cases and the staking deposit CLI, the ONLY thing that changed was the passphrase and the withdrawal address being set up or not.

Each time the command line was:!
sudo ./ethdo validator exit --validator=/home/user/ethdo_folder/keystore_X.json --passphrase=Depends --offline

- Case 1: With withdrawal address, simple passphrase (XxxxXxxx88) --> Worked
- Case 2: No withdrawal address, complex passphrase that starts with a $ ($Xxxx$XxxxXxxx88!) 27 characters in total --> Failed
- Case 3: No withdrawal address, complex passphrase that DOES NOT start with a $ (XxxxxXxxxx$88!) 14 characters in total --> Failed
- Case 4: With withdrawal address, complex passphrase that starts with a $ ($Xxxxx$XxxxXxxx88!) 27 characters in total --> Failed
- Case 5: With withdawal address, complex passphrase that DOES NOT start with a $, 14 characters in total --> Failed

Definitely something wrong with passphrases containing either a $ or a !.

**Comment by mcdee** [comment]
Many shells use $ and ! as special characters.  To avoid them being interpreted by the shell enclose the passphrase with single quotes, e.g. `--passphrase='password1234!"#$'`

**Comment by mcdee** [comment]
Closed due to inactivity.
