### ISSUE TITLE
i can't set withdraw address

### ISSUE THREAD

**Issue by phpmac** [wealdtech/ethdo#84]
./ethdo validator credentials get --validator=xxxx
BLS credentials: 0x00.........

Why didn't you change it? I have tried many times.

```
This validator has exited the system during epoch [xxxx](https://mainnet.beaconcha.in/epoch/xxxx) and is no longer validating. There is no need to keep the validator running anymore. Funds will be withdrawable after epoch [xxxx](https://mainnet.beaconcha.in/epoch/xxxx).
```

https://mainnet.beaconcha.in/validator/xxxx

Because of this Exited status?

https://mainnet.beaconcha.in/tools/broadcast/status/xxxx
This page has not been updated status, what is the problem?

**Comment by mcdee** [comment]
There are tens of thousands of change operations currently waiting to be incorporated on to the chain, it may take up to 5 days until the credentials are updated.
