### ISSUE TITLE
Can't set withdrawal credentials with validator private key

### ISSUE THREAD

**Issue by Sphearis** [wealdtech/ethdo#86]
This command works:
ethdo.exe validator exit --offline --private-key="privkey"

The operation json file is being generated correctly.

But this one doesn't:
ethdo.exe validator credentials set --offline --private-key="privkey" --withdrawal-address="withdrawaladdr"

It leads to this error message: 
Error: failed to process: no validator found with withdrawal credentials 0xsomeothercredential

**Comment by mcdee** [comment]
`privkey` here has to be the private key of the _withdrawal_ credentials.  Are you supply that key?

**Comment by Sphearis** [comment]
My bad, I thought the validator private key was the one needed. I'll try to get that withdrawal credential key from somewhere (node api or deposit/keystores if that's possible)
