### ISSUE TITLE
Ethdo not recognizing the mnemonic from BIP-39

### ISSUE THREAD

**Issue by beetrootkid** [wealdtech/ethdo#89]
Trying to follow the process for bls_to_execution and using the account derive function but receiving a "...Error:failed to process:failed to derive account-mnemonic is invalid" message. (seedphrase has been triple verified as correct and correctly input).

Does ethdo support all the words for BIP-39 seedphrases? Can we add them if not?

**Comment by mcdee** [comment]
The mnemonic wordlists come from github.com/tyler-smith/go-bip39/wordlists and the specific wordlists supported are listed at https://github.com/wealdtech/ethdo/blob/master/util/mnemonic.go#L30=L38

Note that the full mnemonic has to be entered, not just the first 4 characters of each word.

**Comment by beetrootkid** [comment]
Thanks Jim. User error here so apologies for the noise.
