### ISSUE TITLE
Issue installing ethdo

### ISSUE THREAD

**Issue by jedandroby** [wealdtech/ethdo#91]
I seem to be struggling running the first command -  go install github.com/wealdtech/ethdo@latest

its downloading some of it but then failing with this error code;
$ go install github.com/wealdtech/ethdo@latest
# github.com/herumi/bls-eth-go-binary/bls
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:9:28: undefined: SecretKey
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:9:40: undefined: Fr
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:13:26: undefined: Fr
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:13:31: undefined: SecretKey
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:19:28: undefined: PublicKey
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:19:40: undefined: G1
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:23:26: undefined: G1
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:23:31: undefined: PublicKey
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:29:23: undefined: Sign
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:29:30: undefined: G2
..\..\go\pkg\mod\github.com\herumi\bls-eth-go-binary@v1.29.1\bls\cast.go:29:30: too many errors

Meaning i can't get the very first thing done which is installing ethdo. I downloaded latest version of go  (1.20.3) and im using gitbash to try and get ethdo installed.

Mahalo for any help!

**Comment by mcdee** [comment]
I suspect that this is failing due to an older version of the gcc compiler on your computer.  Could you download the latest applicable version from https://sourceforge.net/projects/mingw-w64/ and see if that addresses the issue?

And if you do not need to compile this yourself, you can obtain binaries from https://github.com/wealdtech/ethdo/releases

**Comment by mcdee** [comment]
Closed due to inactivity.
