### ISSUE TITLE
Question: which private key to use for withdrawals when no seed is available

### ISSUE THREAD

**Issue by deetoomon** [wealdtech/ethdo#95]
Hi!

I'm trying to use change withdrawal credentials as described [in your helpful guide](https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md). I do not have my seed phrase avaiable, but I have the validator and withdrawal private keys genereated using the derivation paths `m/12381/3600/0/0/0` and `m/12381/3600/0/0`, respectively. 

My (probably stupid question) is: which key do I use to sign the withdrawal credentials change? Is it one of these keys? Or is it a separate key altogether?

**Comment by mcdee** [comment]
You can supply the withdrawal private key to the command using `--private-key`

**Comment by deetoomon** [comment]
Perfect, thank you @mcdee for the prompt reply!
