### ISSUE TITLE
Issue while preparing offline exit

### ISSUE THREAD

**Issue by Arxis75** [wealdtech/ethdo#96]
Hi

Was giving a try to the following procedure: https://mirror.xyz/ladislaus.eth/wmoBbUBes2Wp1_6DvP6slPabkyujSU7MZOFOC3QpErs

./ethdo validator exit --offline --mnemonic="the_mnemonic" --validator=the_validator_index     gives me the following error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe6621e]

goroutine 1 [running]:
github.com/wealdtech/ethdo/cmd/validator/exit.(*command).validateOperation(0xc000892900?, {0x14c7608?, 0xc0000360c0?})
	/home/me/go/pkg/mod/github.com/wealdtech/ethdo@v1.30.0/cmd/validator/exit/process.go:376 +0x3e
github.com/wealdtech/ethdo/cmd/validator/exit.(*command).process(0xc000892900, {0x14c7608, 0xc0000360c0})
	/home/me/go/pkg/mod/github.com/wealdtech/ethdo@v1.30.0/cmd/validator/exit/process.go:75 +0xaf
github.com/wealdtech/ethdo/cmd/validator/exit.Run(0x1b912c0)
	/home/me/go/pkg/mod/github.com/wealdtech/ethdo@v1.30.0/cmd/validator/exit/run.go:36 +0x65
github.com/wealdtech/ethdo/cmd.glob..func35(0x1b912c0?, {0x1137279?, 0x3?, 0x3?})
	/home/me/go/pkg/mod/github.com/wealdtech/ethdo@v1.30.0/cmd/validatorexit.go:40 +0x1d
github.com/spf13/cobra.(*Command).execute(0x1b912c0, {0xc0004e6ba0, 0x3, 0x3})
	/home/me/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1b8df00)
	/home/me/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/me/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/wealdtech/ethdo/cmd.Execute()
	/home/me/go/pkg/mod/github.com/wealdtech/ethdo@v1.30.0/cmd/root.go:122 +0x25
main.main()
	/home/me/go/pkg/mod/github.com/wealdtech/ethdo@v1.30.0/main.go:19 +0x17

Any idea? 

Thanx in advance

**Comment by Arxis75** [comment]
Sorry that was the command:
./ethdo validator exit --offline --mnemonic="the_mnemonic" --validator=the_index

**Comment by mcdee** [comment]
This suggests that the mnemonic and validator combination supplied do not may to a suitable validator, although obviously it should provide a suitable error rather than crashing.  Worth checking your mnemonic and validator index to ensure that it is correct, and that you have the correct preparation file for the network.

I'm working on an update to the codebase to provide a better system for finding suitable validators to exit (see #88 for comments) which should make this easier, expect to release something later this week.

**Comment by mcdee** [comment]
Version 1.31.0 has been released, which provides additional support for validator exits.  If this does not address your problem please open a new issue; thank you.
